export const ROLES = {
    PROJECT_MANAGER: "PROJECT_MANAGER",
    SCIENTIFIC_SUPERVISOR: "SCIENTIFIC_SUPERVISOR",
    WP_MANAGER: "WP_MANAGER",
    SECTOR_MANAGER: "SECTOR_MANAGER",
    TASK_MANAGER: "TASK_MANAGER",
    ACTIVITY_MANAGER: "ACTIVITY_MANAGER",
    EDITOR: "EDITOR",
    USER: "USER"
};
